# Generated by Django 2.2.24 on 2022-01-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('aadhaarId', models.CharField(help_text='patient aadhaar', max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='patient aadhaar', max_length=20)),
                ('dob', models.DateField(help_text='patient date of birth', max_length=8)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='pateint gender', max_length=1)),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'ordering': ['-name'],
            },
        ),
    ]
