# Generated by Django 2.2.24 on 2022-01-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20220112_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-name'], 'verbose_name': 'patient', 'verbose_name_plural': 'patients'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
    ]
