# Generated by Django 2.2.24 on 2022-01-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20220112_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-last_udpated_on'], 'verbose_name': 'patient', 'verbose_name_plural': 'patients'},
        ),
    ]
