# Generated by Django 2.2.24 on 2022-01-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('aadhaarId', models.CharField(help_text='patient aadhaar no | 12 digit', max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='patient aadhaar', max_length=20)),
                ('date_of_birth', models.DateField(default=None, help_text='patient date of birth', max_length=8)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='pateint gender', max_length=1)),
                ('last_udpated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'ordering': ['-last_udpated_on'],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_weight', models.FloatField()),
                ('height', models.FloatField()),
                ('respiration_rate', models.FloatField()),
                ('pulse_rate', models.FloatField()),
                ('body_temperature', models.FloatField()),
                ('head_circumference', models.FloatField()),
                ('pulse_oximetry', models.FloatField()),
                ('body_mass_index', models.FloatField()),
                ('blood_pressure_systolic', models.FloatField()),
                ('blood_pressure_diastolic', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient_records.Patient')),
            ],
            options={
                'verbose_name': 'vitalsign',
                'verbose_name_plural': 'vitalsigns',
            },
        ),
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tobacco_smoking_status', models.CharField(choices=[('NEVER_SMOKED', 'Never Smoked'), ('CURRENT_SMOKER', 'Current Smoker'), ('FORMER_SMOKER', 'Former Smoker')], default=None, max_length=20)),
                ('alcohol_consumption_status', models.CharField(choices=[('NEVER_DRINKED', 'Lifetime non-drinker'), ('CURRENT_DRINKER', 'Current Drinker'), ('FORMER_DRINKER', 'Former Drinker')], default=None, max_length=20)),
                ('alcohol_consumption_unit', models.IntegerField()),
                ('alcohol_consumption_frequency', models.CharField(max_length=100)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient_records.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=250)),
                ('body_site', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], default=None, max_length=20)),
                ('onset_date', models.DateField(auto_now=True)),
                ('abatement_date', models.DateField()),
                ('diagnostic_certainty', models.CharField(max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='give a short description!', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.Patient')),
            ],
            options={
                'verbose_name': 'medicationstatement',
                'verbose_name_plural': 'medicationstatements',
            },
        ),
        migrations.CreateModel(
            name='MedicationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_item', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('form', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('unit_of_prescription', models.CharField(max_length=100)),
                ('batch_id', models.CharField(max_length=100)),
                ('expiry', models.DateField()),
                ('dose_amount', models.PositiveIntegerField()),
                ('dose_duration', models.CharField(max_length=100)),
                ('dose_unit', models.CharField(max_length=100)),
                ('dose_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('dose_interval', models.CharField(blank=True, max_length=100, null=True)),
                ('dose_specific_timing', models.TimeField()),
                ('route', models.CharField(max_length=100)),
                ('body_site', models.CharField(max_length=100)),
                ('medication_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.MedicationStatement')),
            ],
        ),
    ]
