# Generated by Django 2.2.24 on 2022-01-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_auto_20220113_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body_weight', models.FloatField()),
                ('height', models.FloatField()),
                ('respiration_rate', models.FloatField()),
                ('pulse_rate', models.FloatField()),
                ('body_temperature', models.FloatField()),
                ('head_circumference', models.FloatField()),
                ('pulse_oximetry', models.FloatField()),
                ('body_mass_index', models.FloatField()),
                ('blood_pressure_systolic', models.FloatField()),
                ('blood_pressure_diastolic', models.FloatField()),
                ('ips', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tobacco_smoking_status', models.CharField(choices=[('NEVER_SMOKED', 'Never Smoked'), ('CURRENT_SMOKER', 'Current Smoker'), ('FORMER_SMOKER', 'Former Smoker')], default=None, max_length=20)),
                ('alcohol_consumption_status', models.CharField(choices=[('NEVER_DRINKED', 'Lifetime non-drinker'), ('CURRENT_DRINKER', 'Current Drinker'), ('FORMER_DRINKER', 'Former Drinker')], default=None, max_length=20)),
                ('alcohol_consumption_unit', models.IntegerField()),
                ('alcohol_consumption_frequency', models.CharField(max_length=100)),
                ('ips', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('problem', models.CharField(max_length=250)),
                ('body_site', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], default=None, max_length=20)),
                ('onset_date', models.DateField(auto_now=True)),
                ('abatement_date', models.DateField()),
                ('diagnostic_certainty', models.CharField(max_length=200)),
                ('ips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationStatement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('ips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('medication_item', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('form', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('unit_of_prescription', models.CharField(max_length=100)),
                ('batch_id', models.CharField(max_length=100)),
                ('expiry', models.DateField()),
                ('dose_amount', models.FloatField()),
                ('dose_duration', models.CharField(max_length=100)),
                ('dose_unit', models.CharField(max_length=100)),
                ('dose_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('dose_interval', models.CharField(blank=True, max_length=100, null=True)),
                ('dose_specific_timing', models.TimeField()),
                ('route', models.CharField(max_length=100)),
                ('body_site', models.CharField(max_length=100)),
                ('medication_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.MedicationStatement')),
            ],
        ),
    ]
