# Generated by Django 2.2.24 on 2022-01-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0002_auto_20220114_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationstatement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
