# Generated by Django 2.2.24 on 2022-01-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0002_auto_20220113_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationstatement',
            name='ips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
        migrations.AlterField(
            model_name='problemlist',
            name='ips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='ips',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='ips',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
        migrations.DeleteModel(
            name='InternationalPatientSummary',
        ),
    ]
