# Generated by Django 2.2.24 on 2022-01-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0004_auto_20220115_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
