# Generated by Django 2.2.24 on 2022-01-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0006_auto_20220116_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationitem',
            name='medication_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.MedicationStatement'),
        ),
        migrations.AlterField(
            model_name='medicationstatement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.Patient'),
        ),
    ]
