# Generated by Django 2.2.24 on 2022-01-17 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0007_auto_20220116_1416'),
        ('patient_records', '0005_auto_20220116_0659'),
    ]

    operations = [
    ]
