# Generated by Django 2.2.24 on 2022-01-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0008_merge_20220117_0530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemlist',
            options={'verbose_name_plural': 'ProblemList'},
        ),
        migrations.AlterModelOptions(
            name='socialhistory',
            options={'verbose_name_plural': 'SocialHistory'},
        ),
    ]
