# Generated by Django 2.2.24 on 2022-01-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0008_merge_20220117_0530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-last_updated_on'], 'verbose_name': 'patient', 'verbose_name_plural': 'patients'},
        ),
        migrations.AlterModelOptions(
            name='problemlist',
            options={'verbose_name_plural': 'ProblemList'},
        ),
        migrations.AlterModelOptions(
            name='socialhistory',
            options={'verbose_name_plural': 'SocialHistory'},
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='last_udpated_on',
            new_name='last_updated_on',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='patient gender', max_length=1),
        ),
    ]
