# Generated by Django 2.2.24 on 2022-01-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0009_auto_20220119_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='aadhaarId',
            field=models.CharField(help_text='12 digit aadhar no', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(help_text='YYYY-MM-DD', max_length=8),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='problemlist',
            name='diagnostic_certainty',
            field=models.CharField(choices=[('Suspected', 'Suspected'), ('Probable', 'Probable'), ('Confirmed', 'Confirmed')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='problemlist',
            name='severity',
            field=models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='alcohol_consumption_status',
            field=models.CharField(choices=[('NEVER_DRANK', 'Lifetime non-drinker'), ('CURRENT_DRINKER', 'Current Drinker'), ('FORMER_DRINKER', 'Former Drinker')], default=None, max_length=20),
        ),
    ]
